<?php
define("__HOST__","localhost");
define("__USER__","root");
define("__PASS__","");
define("__DB__","Articles");
define("SITE_FOLDER","PHP-Articles-Website");
define("__RECORDS_PER_PAGE__",4);
define("__Debug__Mode__",0);
?>